/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_floodlightcontroller_learningswitch_NativeClock */

#ifndef _Included_net_floodlightcontroller_learningswitch_NativeClock
#define _Included_net_floodlightcontroller_learningswitch_NativeClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_floodlightcontroller_learningswitch_NativeClock
 * Method:    getCurrentTimeMicros
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_floodlightcontroller_learningswitch_NativeClock_getCurrentTimeMicros
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
